### ISSUE TITLE
the new "Yoast SEO" (or something else) seems to have reverted changes or stopped edits from appearing in the gatsby staging site - do you all know why? 

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#66]
Any idea why this may be? 

For example: #14 #65 #67

**Comment by tbeck** [comment]
Hi @stephtngu - It looks like the build was failing because of a bit of fallback logic related to the source link. This is fixed now as part of the most recent PR. Unfortunately, the build fail was blocking the other changes.

@benrito - Could you invite @stephtngu to the Gatsby Cloud account for visibility into the build status. I am happy to step through the UI and give you a 10cent tour if it helps?

**Comment by stephtngu** [comment]
unfortunately some issues are still persisting - commented on individual issues

**Comment by stephtngu** [comment]
thank you @tbeck !
